//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.zy.android.dowhat;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.ListView;
import com.zy.android.dowhat.R.id;
import com.zy.android.dowhat.R.layout;

public final class TasksActivity_
    extends TasksActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.tasks_activity);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        mAddTask = ((EditText) findViewById(id.main_add_task));
        mTagsListView = ((ListView) findViewById(id.main_tags));
        mTasksListView = ((ListView) findViewById(id.main_tasks));
        {
            View view = findViewById(id.main_add_tag);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        TasksActivity_.this.addTag();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.main_no_tag_tasks);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        TasksActivity_.this.showNoTag();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.main_all_tasks);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        TasksActivity_.this.showAllTasks();
                    }

                }
                );
            }
        }
        loadData();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static TasksActivity_.IntentBuilder_ intent(Context context) {
        return new TasksActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, TasksActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public TasksActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
